version: "3"
tasks:
  new:*:
    vars:
      DIR: "{{index .MATCH 0}}"
    cmds:
      - mkdir -p {{.DIR}}
      - touch {{.DIR}}/solution.go
      - echo "package _{{.DIR}}" | sed "s/-/_/g" > {{.DIR}}/solution.go
      - touch {{.DIR}}/solution_test.go
      - echo "package _{{.DIR}}" | sed "s/-/_/g" > {{.DIR}}/solution_test.go